// GENERATED by scripts/capture.mjs. Do not edit.
//
// Every string below is the server's own answer to tools/list over stdio, or a field of the
// receipt its own health probe wrote. Nothing here was typed by hand, and the punctuation is
// the package's, which is why scripts/check-register.mjs exempts this one file from the dash
// rule by identity.
//
// Captured from /Users/admin/CompoundLabs/compound-mcp
export const SURFACE_CAPTURED_AT = "2026-09-28T13:21:48.173Z";
export const SERVER = {
 "name": "compound-mcp",
 "version": "0.5.0",
 "protocol": "2025-06-18"
} as const;
export const TOOL_COUNT = 11;
export type ToolArg = { name: string; type: string; required: boolean; describe: string };
export type ToolRow = {
  name: string; title: string; description: string;
  group: 'stale' | 'directory' | 'compliance';
  endpoint: { host: string; base: string; key: string };
  annotations: { readOnlyHint: boolean; destructiveHint: boolean; idempotentHint: boolean; openWorldHint: boolean };
  args: ToolArg[]; additionalProperties: boolean;
};
export const TOOLS: ToolRow[] = [
 {
  "name": "lookup_ada_report",
  "title": "Look up an ADA Title II website accessibility report",
  "description": "Look up a US local-government (.gov) domain in the CivicBinder Municipal Web Accessibility Index. Returns the accessibility grade (A-F), WCAG 2.1 AA violation counts from an axe-core scan, the failing rules, the entity's ADA Title II compliance deadline (April 2027 or April 2028), and a link to the full public report page. Use for questions like \"is cityofx.gov ADA compliant\" or \"how accessible is this county website\". Every answer carries a `checked` receipt: when the lookup ran, which index was consulted, and what that index does and does not cover, so the check can be cited later without being re-run.",
  "group": "compliance",
  "endpoint": {
   "host": "xowekqdsttxwbhfxvusa.supabase.co",
   "base": "https://xowekqdsttxwbhfxvusa.supabase.co/rest/v1/cb_ada_scans",
   "key": "civicbinder"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "domain",
    "type": "string",
    "required": true,
    "describe": "The .gov domain to look up, e.g. \"denvergov.org\" or \"cityofmadison.com\". Protocol and paths are stripped automatically."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "lookup_nonprofit_status",
  "title": "Look up nonprofit IRS / California good standing by EIN",
  "description": "Check a US nonprofit's standing by EIN against the IRS auto-revocation list (tax-exempt status revoked for three consecutive missed Form 990 filings) and California Registry of Charities delinquency/suspension lists. Returns revocation and reinstatement dates, whether the streamlined 15-month reinstatement window is still open, and whether AB 488 requires fundraising platforms to block donations. A \"clear\" result means the EIN is on none of the tracked lists. The verdict and the lookup are separate fields: `clear` is the outcome, and the `checked` receipt records when the lookup ran, which lists were consulted, and the limits of that coverage.",
  "group": "compliance",
  "endpoint": {
   "host": "goodstanding.thecompound.tech",
   "base": "https://goodstanding.thecompound.tech/api/lookup",
   "key": "goodstanding"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "ein",
    "type": "string",
    "required": true,
    "describe": "The organization's 9-digit EIN, with or without a dash, e.g. \"12-3456789\"."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "search_agent_configs",
  "title": "Search real AGENTS.md / CLAUDE.md files from public repositories",
  "description": "Search RuleStack, an index of real agent instruction files (AGENTS.md, CLAUDE.md, Cursor rules, Copilot instructions, Windsurf, GEMINI.md, Cline) harvested from public GitHub repositories and scored for quality. Use when writing or reviewing an agent config and you want to see how well-maintained projects with a given stack actually write theirs — \"show me CLAUDE.md files from Next.js repos\", \"what do good AGENTS.md files put in their build section\".",
  "group": "directory",
  "endpoint": {
   "host": "rulestack.thecompound.tech",
   "base": "https://rulestack.thecompound.tech/api",
   "key": "rulestack"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "stack",
    "type": "string",
    "required": false,
    "describe": "Comma-separated stack slugs, ANDed. e.g. \"nextjs,typescript\"."
   },
   {
    "name": "format",
    "type": "string",
    "required": false,
    "describe": "Comma-separated format slugs: agents-md, claude-md, cursor-rules, copilot-instructions, windsurf-rules, gemini-md, cline-rules."
   },
   {
    "name": "tag",
    "type": "string",
    "required": false,
    "describe": "Comma-separated section tags, ANDed: build, test, security, code-style, architecture, git-pr, do-not, docs."
   },
   {
    "name": "min_quality",
    "type": "number",
    "required": false,
    "describe": "Minimum quality score, 0-100."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 5."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "search_agent_skills",
  "title": "Search published Claude Code skills, plugins and marketplaces",
  "description": "Search SkillWorks, an index of publicly published agent skills, plugins and skill marketplaces, ranked by installs and repository signal. Use before writing a skill from scratch to check whether one already exists, or when a user asks \"is there a skill for X\" / \"what should I install for Y\". Returns the install command for each result, so the answer is directly actionable.",
  "group": "directory",
  "endpoint": {
   "host": "skillworks.thecompound.tech",
   "base": "https://skillworks.thecompound.tech/api",
   "key": "skillworks"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "q",
    "type": "string",
    "required": true,
    "describe": "What the skill should do, in plain words. e.g. \"pdf generation\", \"code review\", \"terraform\"."
   },
   {
    "name": "kind",
    "type": "string",
    "required": false,
    "describe": "Filter to one of: skill, subagent, plugin, marketplace."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 5."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "search_component_registries",
  "title": "Search shadcn-style component registries",
  "description": "Search BlockDex, a cross-registry index of shadcn-compatible components, blocks, hooks and libraries from dozens of public registries. Use when a user wants a UI component and you would otherwise hand-write it — \"is there a date range picker block\", \"which registries have a kanban board\". Returns the registry, the item type and its dependencies so you can judge the cost of pulling it in.",
  "group": "directory",
  "endpoint": {
   "host": "blockdex.thecompound.tech",
   "base": "https://blockdex.thecompound.tech/api",
   "key": "blockdex"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "q",
    "type": "string",
    "required": true,
    "describe": "What the component does. e.g. \"data table\", \"auth form\", \"kanban\"."
   },
   {
    "name": "kind",
    "type": "string",
    "required": false,
    "describe": "Filter by item kind: component, block, hook, example, lib, theme, other."
   },
   {
    "name": "access",
    "type": "string",
    "required": false,
    "describe": "Filter by whether the item is free to install: free, paid, unknown."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 5."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "compare_ai_models",
  "title": "Compare current AI model pricing and rankings",
  "description": "Read ToolDrift, which tracks AI model pricing and which models the major AI-powered apps actually route to, sampled nightly. Use when asked which model to use, what a model costs now, or what changed recently — model pricing moves faster than any training cutoff, so answering from memory is reliably wrong.",
  "group": "stale",
  "endpoint": {
   "host": "tooldrift.thecompound.tech",
   "base": "https://tooldrift.thecompound.tech/api",
   "key": "tooldrift"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "board",
    "type": "string",
    "required": false,
    "describe": "Which ranking to read, as \"scope/key\". Budget bands: budget/free, budget/value, budget/balanced, budget/premium. Per-tool routing: tool/claude-code, tool/codex-cli, tool/cline, tool/aider, tool/roo-code, tool/kilo-code. Default overall/all."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many models to return, 1-10. Default 10."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "check_project_maintenance",
  "title": "Check whether a developer tool is still maintained",
  "description": "Read StillShipping, which tracks whether developer tools and libraries are still actively shipping — last release, last commit, and whether the project reads as dead. Use before recommending a dependency. A library that was healthy at training time may have been abandoned since, and this is the check that catches it.",
  "group": "stale",
  "endpoint": {
   "host": "stillshipping.thecompound.tech",
   "base": "https://stillshipping.thecompound.tech/api",
   "key": "stillshipping"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "q",
    "type": "string",
    "required": false,
    "describe": "Tool or library name to look up. Omit to list recently-declared-dead projects."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 5."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "grade_starter_kit",
  "title": "Look up a graded SaaS/Next.js starter kit",
  "description": "Read KitGrade, which installs and grades public starter kits and boilerplates — what is actually wired up (auth, billing, email, tests), what only appears in the README, and how fresh the dependencies are. Use when someone asks which starter to build on.",
  "group": "directory",
  "endpoint": {
   "host": "kitgrade.thecompound.tech",
   "base": "https://kitgrade.thecompound.tech/api",
   "key": "kitgrade"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "q",
    "type": "string",
    "required": false,
    "describe": "Kit name to look up. Omit for the top-graded kits."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 5."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "lookup_service_pricing",
  "title": "Look up current published pricing for a SaaS service",
  "description": "Read StackTab, which re-checks the published pricing of the services a product runs on (auth, database, hosting, payments) and records when each plan was last verified against the vendor's own page. Use when asked what something costs or what its free tier includes. Prices and free-tier limits change often enough that a remembered figure is a guess; each plan here carries the date it was last checked.",
  "group": "stale",
  "endpoint": {
   "host": "stacktab.thecompound.tech",
   "base": "https://stacktab.thecompound.tech/api",
   "key": "stacktab"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "category",
    "type": "string",
    "required": false,
    "describe": "Filter by category: \"auth\", \"database\", \"hosting\" or \"payments\"."
   },
   {
    "name": "service",
    "type": "string",
    "required": false,
    "describe": "A specific service slug or name, e.g. \"clerk\", \"neon\", \"stripe\"."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "estimate_stack_cost",
  "title": "Estimate the monthly bill for a named stack at a given scale",
  "description": "Price a whole stack at a chosen user count using StackTab's verified plan data. Returns the plan each service lands on and an itemised bill — which lines are included in the base fee and which are metered overages. Use when someone asks \"what will this cost at N users\" instead of estimating from memory.",
  "group": "stale",
  "endpoint": {
   "host": "stacktab.thecompound.tech",
   "base": "https://stacktab.thecompound.tech/api",
   "key": "stacktab"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "stack",
    "type": "string",
    "required": true,
    "describe": "Comma-separated service slugs, e.g. \"supabase,clerk,polar,vercel\". Look them up with lookup_service_pricing."
   },
   {
    "name": "users",
    "type": "number",
    "required": false,
    "describe": "Monthly active users to price at. Default 10,000."
   }
  ],
  "additionalProperties": false
 },
 {
  "name": "compare_app_builders",
  "title": "Compare AI app builders on whether their output clears App Store review",
  "description": "Read StoreReady, a sourced comparison of the AI mobile-app builders (Rork, Vibecode, a0.dev, Replit, Bolt and the rest) on one question: can the app it hands you go up on your own Apple Developer account and survive review. Returns what each builder outputs, whether you can export the source, who submits the binary, the App Store guidelines in play, and a verdict of ships / ships-with-caveats / blocked / unknown. Use when asked which AI app builder to pick, or whether one can actually ship to the App Store — the answer changes as builders launch and change, and every verdict here is attached to a source that was read on a stated date.",
  "group": "directory",
  "endpoint": {
   "host": "storeready.thecompound.tech",
   "base": "https://storeready.thecompound.tech/api",
   "key": "storeready"
  },
  "annotations": {
   "readOnlyHint": true,
   "destructiveHint": false,
   "idempotentHint": true,
   "openWorldHint": true
  },
  "args": [
   {
    "name": "builder",
    "type": "string",
    "required": false,
    "describe": "One builder slug or name for the full record with its evidence, e.g. \"rork\", \"vibecode\", \"bolt\"."
   },
   {
    "name": "verdict",
    "type": "string",
    "required": false,
    "describe": "Filter the list: ships, ships-with-caveats, blocked, unknown."
   },
   {
    "name": "limit",
    "type": "number",
    "required": false,
    "describe": "How many to return, 1-10. Default 10."
   }
  ],
  "additionalProperties": false
 }
];
export const PROBE = {
 "checked_at": "2026-09-28T08:46:54.735Z",
 "repo_version": "0.5.0",
 "protocol_version": "2025-11-25",
 "server_version": "0.5.0",
 "tool_count": 11,
 "endpoints_checked": 10,
 "endpoints_failed": 0,
 "duration_ms": 6320,
 "failing": [],
 "endpoints": [
  {
   "name": "civicbinder-ada",
   "url": "https://xowekqdsttxwbhfxvusa.supabase.co/rest/v1/cb_ada_scans?status=eq.scanned&select=domain&limit=1",
   "http": 200,
   "bytes": 28,
   "ms": 176,
   "ok": true
  },
  {
   "name": "goodstanding",
   "url": "https://goodstanding.thecompound.tech/api/lookup?q=475262842",
   "http": 200,
   "bytes": 293,
   "ms": 92,
   "ok": true
  },
  {
   "name": "rulestack",
   "url": "https://rulestack.thecompound.tech/api/configs?limit=1",
   "http": 200,
   "bytes": 1816,
   "ms": 769,
   "ok": true
  },
  {
   "name": "skillworks",
   "url": "https://skillworks.thecompound.tech/api/list?limit=1",
   "http": 200,
   "bytes": 2379,
   "ms": 456,
   "ok": true
  },
  {
   "name": "blockdex",
   "url": "https://blockdex.thecompound.tech/api/search?q=button&limit=1",
   "http": 200,
   "bytes": 4207,
   "ms": 6297,
   "ok": true
  },
  {
   "name": "tooldrift",
   "url": "https://tooldrift.thecompound.tech/api/leaderboard",
   "http": 200,
   "bytes": 126178,
   "ms": 337,
   "ok": true
  },
  {
   "name": "stillshipping",
   "url": "https://stillshipping.thecompound.tech/api/dead?limit=1",
   "http": 200,
   "bytes": 42028,
   "ms": 195,
   "ok": true
  },
  {
   "name": "kitgrade",
   "url": "https://kitgrade.thecompound.tech/api/kits?limit=1",
   "http": 200,
   "bytes": 613,
   "ms": 118,
   "ok": true
  },
  {
   "name": "stacktab",
   "url": "https://stacktab.thecompound.tech/api/catalogue",
   "http": 200,
   "bytes": 69594,
   "ms": 384,
   "ok": true
  },
  {
   "name": "storeready",
   "url": "https://storeready.thecompound.tech/api/builders",
   "http": 200,
   "bytes": 21749,
   "ms": 198,
   "ok": true
  }
 ],
 "outcomes": [
  {
   "tool": "lookup_nonprofit_status",
   "ms": 204,
   "ok": true
  },
  {
   "tool": "lookup_ada_report",
   "ms": 157,
   "ok": true
  },
  {
   "tool": "compare_ai_models",
   "ms": 269,
   "ok": true
  }
 ]
} as const;
